version: '3'
services:
  tg-adapter:
    image: ghcr.io/kyledevops/alertmanager-tg-adapter:main
    pull_policy: always
    container_name: tg-adapter
    restart: always
    ports:
      - "9087:9087"
    volumes:
      - ./config.yml:/app/config.yml
    environment:
      - CONFIG_FILE=/app/config.yml
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9087/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
